### ISSUE TITLE
Problems with OSGI context

### ISSUE THREAD

**Issue by alienatorZ** [akquinet/vaangular#4]
When used as a bundle in an OSGI project starting with NgTemplatePlus.java line 61 a null pointer is thrown do to the difference in loading resources in OSGI.

**Comment by sebastianrothbucher** [comment]
Hi, that's trange as the line seems blank. Guessing it's 60 or 62, would it help to include elemantal.json as another OSGI dependency?

**Comment by alienatorZ** [comment]
Yes, I apologize. It is line 62.  I found this stackoverflow talking about it. http://stackoverflow.com/questions/6474634/how-do-i-access-a-file-inside-an-osgi-bundle

Simply doing a "new File(...)" apparently does not work. I get a Null Pointer Exeption beginning with line 62 in an OSGI context.

**Comment by sebastianrothbucher** [comment]
ok, now I get it. It should be a ```getClass().getResourceAsStream()``` somehow. Would the ```NgTemplatePlus(String templateSource, String moduleName)``` constructor help with that?

**Comment by alienatorZ** [comment]
Yes I think If I use get ResourceAsStream and put the result into NgTemplatePlus(String templateSource, String moduleName) that will work.

Thank you!
